579
string
./operator/add_bool_nil.lox:1:1: Operands to '+' must both be numbers or strings.
./operator/add_bool_num.lox:1:1: Operands to '+' must both be numbers or strings.
./operator/add_bool_string.lox:1:1: Operands to '+' must both be numbers or strings.
./operator/add_nil_nil.lox:1:1: Operands to '+' must both be numbers or strings.
./operator/add_num_nil.lox:1:1: Operands to '+' must both be numbers or strings.
./operator/add_string_nil.lox:1:3: Operands to '+' must both be numbers or strings.
true
false
false
true
true
false
false
false
true
false
true
true
false
false
false
false
true
true
true
true
4
1
./operator/divide_nonnum_num.lox:1:3: Operands to '/' must both be numbers.
./operator/divide_num_nonnum.lox:1:1: Operands to '/' must both be numbers.
true
true
false
true
false
true
false
false
false
false
false
false
false
false
false
false
false
false
true
false
./operator/greater_nonnum_num.lox:1:3: Operands to '>' must both be numbers.
./operator/greater_num_nonnum.lox:1:1: Operands to '>' must both be numbers.
./operator/greater_or_equal_nonnum_num.lox:1:3: Operands to '>=' must both be numbers.
./operator/greater_or_equal_num_nonnum.lox:1:1: Operands to '>=' must both be numbers.
./operator/less_nonnum_num.lox:1:3: Operands to '<' must both be numbers.
./operator/less_num_nonnum.lox:1:1: Operands to '<' must both be numbers.
./operator/less_or_equal_nonnum_num.lox:1:3: Operands to '<=' must both be numbers.
./operator/less_or_equal_num_nonnum.lox:1:1: Operands to '<=' must both be numbers.
15
3.702
./operator/multiply_nonnum_num.lox:1:3: Operands to '*' must both be numbers.
./operator/multiply_num_nonnum.lox:1:1: Operands to '*' must both be numbers.
-3
3
-3
./operator/negate_nonnum.lox:1:1: Operand to '-' must be a number.
false
true
true
false
false
true
false
false
false
false
false
false
true
false
true
false
true
true
true
true
1
0
./operator/subtract_nonnum_num.lox:1:3: Operands to '-' must both be numbers.
./operator/subtract_num_nonnum.lox:1:1: Operands to '-' must both be numbers.
